version: 2

sources:
    - name: dsr_input
      description: Standard input tables for all inbound DSR data.
      database: AA_DSR_RAW
      tables:
        - name: input_pln_inv_storedaysku
          description: '{{ doc("input_pln_inv_storedaysku") }}'
          tests:
            - unique_combination_of_columns:
                combination_of_columns:
                  - day_date
                  - source_db_id
                  - organisation_sku
                  - ranged
                  - organisation_location_id
                  - loaded_timestamp
                env: prod
          columns:
            - name: created_timestamp
              description: '{{ doc("created_timestamp") }}'
            - name: day_date
              description: '{{ doc("day_date") }}'
              tests:
                - not_null:
                    env: prod
            - name: loaded_timestamp
              description: '{{ doc("loaded_timestamp") }}'
            - name: organisation_location_id
              description: '{{ doc("organisation_location_id") }}'
              tests:
                - not_null:
                    env: prod
            - name: organisation_sku
              description: '{{ doc("organisation_sku") }}'
              tests:
                - not_null:
                    env: prod
            - name: ranged
              description: '{{ doc("ranged") }}'
              tests:
                - not_null:
                    env: prod
            - name: source_db_id
              description: '{{ doc("source_db_id") }}'
              tests:
                - not_null:
                    env: prod
