version: 2

sources:
    - name: dsr_input
      description: Standard input tables for all inbound DSR data.
      database: AA_DSR_RAW
      tables:
        - name: input_pln_inv_storedaysku
          description: Raw product data from origin organisations.
          tests:
            - dbt_utils.unique_combination_of_columns:
                combination_of_columns:
                  - day_date
                  - source_db_id
                  - organisation_sku
                  - ranged
                  - organisation_location_id
                  - loaded_timestamp
          columns:
            - name: source_db_id
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null
            - name: day_date
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null
            - name: organisation_sku
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null
            - name: ranged
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null
            - name: organisation_location_id
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null
models:
  - name: stg_pln_inv_storedaysku
    columns:
      - name: unique_key
        tests:
          - check_distinct_sku_fetched:
              env: ci
          - check_all_sku_fetched:
             columnlist:
              - day_date
              - source_db_id
              - organisation_location_id
              - organisation_sku
              - ranged
             env: ci
          - check_latest_sku_fetched:
              columnlist:
              - day_date
              - source_db_id
              - organisation_location_id
              - organisation_sku
              - ranged
              env: ci
      - name: source_db_id
        tests:
          - relationships:
              to: ref('utl_source_organisations')
              field: business_organisation_number
      - name: organisation_location_id
        tests:
          - relationships:
              to: ref('dim_location')
              field: organisation_location_id
      - name: organisation_sku
        tests:
          - relationships:
              to: ref('dim_product')
              field: organisation_sku
