version: 2

sources:
    - name: dsr_input
      description: Standard input tables for all inbound DSR data.
      database: AA_DSR_RAW
      tables:
        - name: input_pln_inv_storedaysku
          description: '{{ doc("input_pln_inv_storedaysku") }}'
          tests:
            - unique_combination_of_columns:
                combination_of_columns:
                  - day_date
                  - source_db_id
                  - organisation_sku
                  - ranged
                  - organisation_location_id
                  - loaded_timestamp
                env: prod
          columns:
            - name: created_timestamp
              description: '{{ doc("created_timestamp") }}'
            - name: day_date
              description: '{{ doc("day_date") }}'
              tests:
                - not_null:
                    env: prod
            - name: loaded_timestamp
              description: '{{ doc("loaded_timestamp") }}'
            - name: organisation_location_id
              description: '{{ doc("organisation_location_id") }}'
              tests:
                - not_null:
                    env: prod
            - name: organisation_sku
              description: '{{ doc("organisation_sku") }}'
              tests:
                - not_null:
                    env: prod
            - name: ranged
              description: '{{ doc("ranged") }}'
              tests:
                - not_null:
                    env: prod
            - name: source_db_id
              description: '{{ doc("source_db_id") }}'
              tests:
                - not_null:
                    env: prod


models:
  - name: stg_pln_inv_storedaysku
    description: '{{ doc("stg_pln_inv_storedaysku") }}'
    columns:
      - name: unique_key
        tests:
          - check_distinct_sku_fetched:
              env: ci
          - check_all_sku_fetched:
             columnlist:
              - day_date
              - source_db_id
              - organisation_location_id
              - organisation_sku
              - ranged
             env: ci
          - check_latest_sku_fetched:
              columnlist:
              - day_date
              - source_db_id
              - organisation_location_id
              - organisation_sku
              - ranged
              env: ci
      - name: source_db_id
        tests:
          - relationships:
              to: ref('utl_source_organisations')
              field: business_organisation_number
      - name: organisation_location_id
        tests:
          - relationships:
              to: ref('dim_location')
              field: organisation_location_id
      - name: organisation_sku
        tests:
          - relationships:
              to: ref('dim_product')
              field: organisation_sku
