version: 2

sources:
    - name: dsr_input
      description: Standard input tables for all inbound DSR data.
      database: AA_DSR_RAW
      tables:
        - name: input_pln_inv_storedaysku
          description: Raw product data from origin organisations.
          tests:
            - dbt_utils.unique_combination_of_columns:
                combination_of_columns:
                  - day_date
                  - source_db_id
                  - organisation_sku
                  - ranged
                  - organisation_location_id
                  - loaded_timestamp
          columns:
            - name: source_db_id
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null
            - name: day_date
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null
            - name: organisation_sku
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null
            - name: ranged
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null
            - name: organisation_location_id
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null

