version: 2

sources:
    - name: dsr_input
      description: Standard input tables for all inbound DSR data.
      database: AA_DSR_RAW
      tables:
        - name: input_act_inv_locationdaysku
          description: Raw store order metrics from source databases
          tests:
            - dbt_utils.unique_combination_of_columns:
                combination_of_columns:
                  - day_date
                  - source_db_id
                  - organisation_sku
                  - stock_units
                  - location_function
                  - organisation_location_id
                  - loaded_timestamp
          columns:
            - name: source_db_id
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null
            - name: day_date
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null
            - name: organisation_sku
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null
            - name: stock_units
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null
            - name: location_function
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null
            - name: organisation_location_id
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null


        - name: input_act_inv_locationdaycase
          description: Raw store order metrics from source databases
          tests:
            - dbt_utils.unique_combination_of_columns:
                combination_of_columns:
                  - day_date
                  - source_db_id
                  - organisation_case
                  - stock_units
                  - location_function
                  - organisation_location_id
                  - loaded_timestamp
          columns:
            - name: source_db_id
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null
            - name: day_date
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null
            - name: organisation_case
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null
            - name: stock_units
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null
            - name: location_function
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null
            - name: organisation_location_id
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null