version: 2

sources:
    - name: dsr_input
      description: Standard input tables for all inbound DSR data.
      database: AA_DSR_RAW
      tables:
        - name: input_act_inv_locationdaysku
          description: Raw store order metrics from source databases
          tests:
            - unique_combination_of_columns:
                combination_of_columns:
                  - day_date
                  - source_db_id
                  - organisation_sku
                  - stock_units
                  - location_function
                  - organisation_location_id
                  - loaded_timestamp
                env: prod
          columns:
            - name: source_db_id
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null:
                    env: prod
            - name: day_date
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null:
                    env: prod
            - name: organisation_sku
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null:
                    env: prod
            - name: location_function
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null:
                    env: prod
            - name: organisation_location_id
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null:
                    env: prod


        - name: input_act_inv_locationdaycase
          description: Raw store order metrics from source databases
          tests:
            - unique_combination_of_columns:
                combination_of_columns:
                  - day_date
                  - source_db_id
                  - organisation_case
                  - stock_units
                  - location_function
                  - organisation_location_id
                  - loaded_timestamp
                env: prod
          columns:
            - name: source_db_id
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null:
                    env: prod
            - name: day_date
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null:
                    env: prod
            - name: organisation_case
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null:
                    env: prod
            - name: stock_units
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null:
                    env: prod
            - name: location_function
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null:
                    env: prod
            - name: organisation_location_id
              description: Number assigned to the organisation by the origin organisation.
              tests:
                - not_null:
                    env: prod

models:
  - name: stg_act_inv_locationdaycase
    description: '{{ doc("stg_act_inv_locationdaycase") }}'
    columns:
      - name: unique_key
        tests:
          - check_distinct_sku_fetched:
              env: ci
          - check_all_sku_fetched:
             columnlist:
              - day_date
              - source_db_id
              - organisation_location_id
              - organisation_case
              - location_function
             env: ci
          - check_latest_sku_fetched:
              columnlist:
              - day_date
              - source_db_id
              - organisation_location_id
              - organisation_case
              - location_function
              env: ci
      - name: source_db_id
        tests:
          - relationships:
              to: ref('utl_source_organisations')
              field: business_organisation_number
      - name: organisation_location_id
        tests:
          - relationships:
              to: ref('dim_location')
              field: organisation_location_id
      - name: location_function
        tests:
          - relationships:
              to: ref('dim_location')
              field: location_function
      - name: organisation_case
        tests:
          - relationships:
              to: ref('dim_logisticitem')
              field: organisation_case
  - name: stg_act_inv_locationdaysku
    description: '{{ doc("stg_act_inv_locationdaysku") }}'
    columns:
      - name: unique_key
        tests:
          - check_distinct_sku_fetched:
              env: ci
          - check_all_sku_fetched:
             columnlist:
              - day_date
              - source_db_id
              - organisation_location_id
              - organisation_sku
              - location_function
             env: ci
          - check_latest_sku_fetched:
              columnlist:
              - day_date
              - source_db_id
              - organisation_location_id
              - organisation_sku
              - location_function
              env: ci
      - name: source_db_id
        tests:
          - relationships:
              to: ref('utl_source_organisations')
              field: business_organisation_number
      - name: organisation_location_id
        tests:
          - relationships:
              to: ref('dim_location')
              field: organisation_location_id
      - name: location_function
        tests:
          - relationships:
              to: ref('dim_location')
              field: location_function
      - name: organisation_sku
        tests:
          - relationships:
              to: ref('dim_product')
              field: organisation_sku